builders:
  dart_ts_generator:
    import: "package:dart_ts_generator/builder.dart"
    builder_factories: ["dartTsGeneratorBuilder"]
    build_extensions:
      ".dart": [".g.ts"]
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        include:
          - lib/models/**
          - lib/src/models/**

  dart_ts_file_builder:
    import: "package:dart_ts_generator/builder.dart"
    builder_factories: ["dartTsFileBuilder"]
    build_extensions:
      ".dart": [".g.ts"]
    auto_apply: none
    build_to: source

  dart_ts_index_builder:
    import: "package:dart_ts_generator/index_builder.dart"
    builder_factories: ["tsIndexBuilder"]
    build_extensions:
      r"$lib$": ["generated/ts/index.ts"]
    auto_apply: none
    build_to: source
    runs_before:
      - dart_ts_generator:dart_ts_generator

targets:
  $default:
    builders:
      dart_ts_generator:dart_ts_generator:
        enabled: true
        options:
          output_dir: "lib/generated/ts"
          generate_index: true
          zod_import: "zod"
          firestore_transforms: true
          null_safety: true
