/// Tracks which schemas are defined in which files so the generator
/// can emit correct `import` statements when referencing cross-file types.
///
/// Example:
///   EiModel is defined in ei_model.dart → generates ei_model.g.ts
///   EiUser extends EiModel (in ei_user.dart) → needs:
///     import { EiModelSchema } from './ei_model.g';
library;

import 'package:path/path.dart' as p;

/// Holds a registry of [typeName → sourceFile] mappings accumulated
/// across an entire build run.
class CrossFileRegistry {
  /// Map from class/enum name → the .g.ts file path (relative to output root)
  final Map<String, String> _typeToFile = {};

  /// Map from .g.ts file → list of type names defined there
  final Map<String, List<String>> _fileToTypes = {};

  void registerTypes(String outputFilePath, List<String> typeNames) {
    for (final name in typeNames) {
      _typeToFile[name] = outputFilePath;
    }
    _fileToTypes[outputFilePath] = typeNames;
  }

  /// Returns the output file path where [typeName] is defined,
  /// or null if it's defined in the same file (no import needed).
  String? fileForType(String typeName) => _typeToFile[typeName];

  /// Given the current file and a referenced type, return the relative
  /// import path (without extension), or null if same-file.
  String? importPathFor(String currentFile, String referencedType) {
    final targetFile = _typeToFile[referencedType];
    if (targetFile == null || targetFile == currentFile) return null;

    final currentDir = p.dirname(currentFile);
    var rel = p.relative(targetFile, from: currentDir);

    // Remove .ts extension for TS imports
    if (rel.endsWith('.ts')) {
      rel = rel.substring(0, rel.length - 3);
    }

    // Ensure ./ prefix
    if (!rel.startsWith('.')) rel = './$rel';

    return rel;
  }

  bool hasType(String name) => _typeToFile.containsKey(name);
}

/// Generates an `index.ts` barrel file that re-exports all generated schemas.
class IndexBarrelGenerator {
  static String generate(List<String> outputFiles, String indexFilePath) {
    final buf = StringBuffer();
    buf.writeln('// AUTO-GENERATED by dart_ts_generator. DO NOT EDIT.');
    buf.writeln('// Barrel re-export of all generated schemas.');
    buf.writeln();

    final indexDir = p.dirname(indexFilePath);

    for (final file in outputFiles) {
      var rel = p.relative(file, from: indexDir);
      if (rel.endsWith('.ts')) rel = rel.substring(0, rel.length - 3);
      if (!rel.startsWith('.')) rel = './$rel';
      buf.writeln("export * from '$rel';");
    }

    return buf.toString();
  }
}

/// Generates cross-file import headers for a single output file.
class ImportHeaderGenerator {
  static String generate({
    required String currentFile,
    required List<String> referencedTypes,
    required CrossFileRegistry registry,
    required String zodImport,
  }) {
    final buf = StringBuffer();
    buf.writeln("import { z } from '$zodImport';");

    // Group referenced types by their source file
    final importMap = <String, List<String>>{};

    for (final type in referencedTypes) {
      final importPath = registry.importPathFor(currentFile, type);
      if (importPath != null) {
        importMap.putIfAbsent(importPath, () => []).add('${type}Schema');
      }
    }

    for (final entry in importMap.entries.toList()..sort((a, b) => a.key.compareTo(b.key))) {
      final symbols = entry.value.join(', ');
      buf.writeln("import { $symbols } from '${entry.key}';");
    }

    return buf.toString();
  }
}
