import 'package:analyzer/dart/element/element.dart';

class EnumEmitter {
  static Map<String, dynamic> extractMetadata(EnumElement enm) {
    return {
      'name': enm.name,
      'values':
          enm.fields.where((f) => f.isEnumConstant).map((f) => f.name).toList(),
    };
  }

  static String emit(List<Map<String, dynamic>> enums) {
    if (enums.isEmpty) return '// No enums found.\n';
    final buf = StringBuffer();
    buf.writeln('// Auto-generated by ts_codegen. Do not edit manually.');
    buf.writeln();

    for (final enm in enums) {
      final name = enm['name'] as String;
      final values = (enm['values'] as List).cast<String>();
      buf.writeln('export enum $name {');
      for (final v in values) {
        buf.writeln("  $v = '$v',");
      }
      buf.writeln('}');
      buf.writeln();
    }

    return buf.toString();
  }
}
