import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'type_mapper.dart';

class ModelEmitter {
  /// Extract serializable metadata from a ClassElement into plain JSON
  /// so it can be cached and passed between builder phases.
  static Map<String, dynamic> extractMetadata(ClassElement cls) {
    final fields = <Map<String, dynamic>>[];

    for (final field in cls.fields) {
      if (field.isStatic) continue;
      if ((field.firstFragment.nameOffset ?? 0) < 0) continue;
      if (field.name == 'hashCode' || field.name == 'runtimeType') continue;

      final converterType = TypeMapper.converterOverride(field);
      final jsonName = TypeMapper.jsonKeyName(field) ?? field.name;
      final tsType = converterType ?? TypeMapper.map(field.type);
      final isOptional =
          field.type.nullabilitySuffix == NullabilitySuffix.question ||
              tsType.contains('| undefined');

      // Derive base type (strip [] and | undefined)
      final stripped = tsType.replaceAll(' | undefined', '');
      final isArray = stripped.endsWith('[]');
      final baseType = isArray ? stripped.replaceAll('[]', '') : stripped;

      // Detect special semantic types
      final isDate = baseType == 'Date';
      final isGeoPoint = baseType == 'GeoPoint';
      final isEmail = TypeMapper.hasEmailAnnotation(field);

      // Detect default value presence from Dart initializer
      final hasDefault = field.hasInitializer;

      fields.add({
        'name': field.name,
        'jsonName': jsonName,
        'tsType': tsType,
        'baseType': baseType,
        'isOptional': isOptional,
        'isArray': isArray,
        'isDate': isDate,
        'isGeoPoint': isGeoPoint,
        'isEmail': isEmail,
        'hasDefault': hasDefault,
        'hasConverter': converterType != null,
      });
    }

    // Determine superclass (for extends)
    final superName = cls.supertype?.element.name;
    final extendsClass =
        (superName != null && superName != 'Object') ? superName : null;

    // Check if class should emit a static copy() method
    // (classes that have a superclass or are non-trivial models)
    final hasCopy = extendsClass != null;

    return {
      'name': cls.name,
      'fields': fields,
      'extends': extendsClass,
      'hasCopy': hasCopy,
    };
  }

  /// Aggregate all model metadata and emit a complete models.ts file.
  static String emit(
    List<Map<String, dynamic>> models,
    List<Map<String, dynamic>> enums,
  ) {
    final enumNames = enums.map((e) => e['name'] as String).toSet();
    final modelNames = models.map((m) => m['name'] as String).toSet();
    final buf = StringBuffer();

    buf.writeln('// Auto-generated by ts_codegen. Do not edit manually.');
    buf.writeln();

    // ── Imports ──────────────────────────────────────────────────────────
    buf.writeln(
        "import { Type, instanceToPlain, plainToInstance } from 'class-transformer';");
    buf.writeln(
        "import { IsArray, IsBoolean, IsEmail, IsEnum, IsNumber, IsString, ValidateNested } from 'class-validator';");
    buf.writeln(
        "import { OptionalNested, OptionalValue, TransformDate, TransformGeoPoint } from './utils';");

    if (enumNames.isNotEmpty) {
      buf.writeln("import { ${enumNames.join(', ')} } from './enums';");
    }

    buf.writeln();

    // ── Classes ───────────────────────────────────────────────────────────
    for (final model in models) {
      buf.write(_emitClass(model, modelNames, enumNames));
    }

    return buf.toString();
  }

  static String _emitClass(
    Map<String, dynamic> model,
    Set<String> modelNames,
    Set<String> enumNames,
  ) {
    final name = model['name'] as String;
    final fields = (model['fields'] as List).cast<Map<String, dynamic>>();
    final extendsClass = model['extends'] as String?;
    final hasCopy = model['hasCopy'] as bool? ?? false;
    final buf = StringBuffer();

    final extendsPart = extendsClass != null ? ' extends $extendsClass' : '';
    buf.writeln('export class $name$extendsPart {');

    // ── Field declarations with decorators ────────────────────────────
    for (final f in fields) {
      _emitField(buf, f, modelNames, enumNames);
    }

    // ── Constructor ───────────────────────────────────────────────────
    buf.writeln();
    buf.writeln('  constructor(data?: Partial<$name>) {');
    if (extendsClass != null) {
      buf.writeln('    super(data);');
    }
    buf.writeln('    if (data) {');
    buf.writeln('      Object.assign(this, data);');
    buf.writeln('    }');
    buf.writeln('  }');

    // ── fromJson ──────────────────────────────────────────────────────
    buf.writeln();
    buf.writeln('  static fromJson(json: unknown): $name {');
    buf.writeln('    return plainToInstance($name, json, {');
    buf.writeln('      exposeDefaultValues: true,');
    buf.writeln('      enableImplicitConversion: true,');
    buf.writeln('    });');
    buf.writeln('  }');

    // ── toJson ────────────────────────────────────────────────────────
    buf.writeln();
    buf.writeln('  toJson(): Record<string, any> {');
    buf.writeln('    return instanceToPlain(this, {');
    buf.writeln('      exposeUnsetFields: false,');
    buf.writeln('      enableImplicitConversion: true,');
    buf.writeln('    });');
    buf.writeln('  }');

    // ── copy() — only for classes that extend another model ───────────
    if (hasCopy) {
      buf.writeln();
      buf.writeln('  static copy(r: $name): $name {');
      buf.writeln('    return $name.fromJson(instanceToPlain(r));');
      buf.writeln('  }');
    }

    buf.writeln('}');
    buf.writeln();

    return buf.toString();
  }

  static void _emitField(
    StringBuffer buf,
    Map<String, dynamic> field,
    Set<String> modelNames,
    Set<String> enumNames,
  ) {
    final name = field['name'] as String;
    final tsType = field['tsType'] as String;
    final baseType = field['baseType'] as String;
    final isOptional = field['isOptional'] as bool;
    final isArray = field['isArray'] as bool;
    final isDate = field['isDate'] as bool;
    final isGeoPoint = field['isGeoPoint'] as bool;
    final isEmail = field['isEmail'] as bool;
    // final hasConverter = field['hasConverter'] as bool;
    // final hasDefault = field['hasDefault'] as bool? ?? false;
    final isNested = modelNames.contains(baseType);
    final isEnum = enumNames.contains(baseType);

    // ── Choose the right decorator pattern ────────────────────────────
    //
    // Rule: a field is "optional" in the EiModel sense when it is nullable
    // (Dart T?). Required fields get straight validators; optional fields get
    // wrapped in OptionalValue() or OptionalNested().
    //
    // Nested model → OptionalNested / ValidateNested+Type
    // Date         → OptionalValue + TransformDate  (or TransformListDate for arrays)
    // GeoPoint     → OptionalValue + TransformGeoPoint
    // Everything else optional → @OptionalValue()
    // Everything else required → plain validator

    if (isNested) {
      if (isOptional) {
        buf.writeln('  @OptionalNested(() => $baseType)');
      } else if (isArray) {
        buf.writeln('  @IsArray()');
        buf.writeln('  @ValidateNested({ each: true })');
        buf.writeln('  @Type(() => $baseType)');
      } else {
        buf.writeln('  @ValidateNested()');
        buf.writeln('  @Type(() => $baseType)');
      }
    } else if (isDate) {
      if (isOptional) buf.writeln('  @OptionalValue()');
      if (isArray) {
        buf.writeln('  @TransformListDate()');
      } else {
        buf.writeln('  @TransformDate()');
      }
    } else if (isGeoPoint) {
      if (isOptional) buf.writeln('  @OptionalValue()');
      buf.writeln('  @TransformGeoPoint()');
    } else {
      // Primitive / enum / string / number / boolean
      if (isOptional) buf.writeln('  @OptionalValue()');

      if (isEnum) {
        buf.writeln('  @IsEnum($baseType)');
      } else if (isEmail) {
        buf.writeln('  @IsEmail()');
      } else if (isArray) {
        buf.writeln('  @IsArray()');
        buf.writeln('  @IsString({ each: true })');
      } else {
        switch (baseType) {
          case 'string':
            buf.writeln('  @IsString()');
            break;
          case 'number':
            buf.writeln('  @IsNumber()');
            break;
          case 'boolean':
            buf.writeln('  @IsBoolean()');
            break;
        }
      }
    }

    // ── Field declaration ─────────────────────────────────────────────
    final optMark = isOptional ? '?' : '';
    buf.writeln('  $name$optMark: $tsType;');
    buf.writeln();
  }
}
