import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'type_mapper.dart';

class ModelEmitter {
  /// Extract serializable metadata from a ClassElement into plain JSON
  /// so it can be cached and passed between builder phases.
  static Map<String, dynamic> extractMetadata(ClassElement cls) {
    final fields = <Map<String, dynamic>>[];

    for (final field in cls.fields) {
      if (field.isStatic) continue;
      if ((field.firstFragment.nameOffset ?? 0) < 0) continue;
      if (field.name == 'hashCode' || field.name == 'runtimeType') continue;

      final converterType = TypeMapper.converterOverride(field);
      final jsonName = TypeMapper.jsonKeyName(field) ?? field.name;
      final tsType = converterType ?? TypeMapper.map(field.type);
      final isOptional =
          field.type.nullabilitySuffix == NullabilitySuffix.question ||
              tsType.contains('| undefined');

      fields.add({
        'name': field.name,
        'jsonName': jsonName,
        'tsType': tsType,
        'isOptional': isOptional,
        'hasConverter': converterType != null,
      });
    }

    // Determine superclass (for extends)
    final superName = cls.supertype?.element.name;
    final extendsClass =
        (superName != null && superName != 'Object') ? superName : null;

    return {
      'name': cls.name,
      'fields': fields,
      'extends': extendsClass,
    };
  }

  /// Aggregate all model metadata and emit a complete models.ts file.
  static String emit(
    List<Map<String, dynamic>> models,
    List<Map<String, dynamic>> enums,
  ) {
    final enumNames = enums.map((e) => e['name'] as String).toSet();
    final modelNames = models.map((m) => m['name'] as String).toSet();
    final buf = StringBuffer();

    buf.writeln('// Auto-generated by ts_codegen. Do not edit manually.');
    buf.writeln("import 'reflect-metadata';");
    buf.writeln(
        "import { Type, Expose, Exclude, plainToInstance, instanceToPlain, Transform } from 'class-transformer';");
    buf.writeln(
        "import { IsString, IsOptional, IsEnum, IsDate, ValidateNested, IsBoolean, IsNumber } from 'class-validator';");
    buf.writeln(
        "import { firestoreTimestampToDate, dateToFirestoreTimestamp } from './utils';");

    if (enumNames.isNotEmpty) {
      buf.writeln("import { ${enumNames.join(', ')} } from './enums';");
    }

    buf.writeln();

    for (final model in models) {
      buf.write(_emitClass(model, modelNames, enumNames));
    }

    return buf.toString();
  }

  static String _emitClass(
    Map<String, dynamic> model,
    Set<String> modelNames,
    Set<String> enumNames,
  ) {
    final name = model['name'] as String;
    final fields = (model['fields'] as List).cast<Map<String, dynamic>>();
    final extendsClass = model['extends'] as String?;
    final buf = StringBuffer();

    final extendsPart = extendsClass != null ? ' extends $extendsClass' : '';
    buf.writeln('export class $name$extendsPart {');

    // Fields with decorators
    for (final f in fields) {
      _emitField(buf, f, modelNames, enumNames);
    }

    // Constructor
    buf.writeln();
    buf.writeln('  constructor(partial?: Partial<$name>) {');
    if (extendsClass != null)
      buf.writeln('    super(partial as Partial<$extendsClass>);');
    buf.writeln('    Object.assign(this, partial);');
    buf.writeln('  }');

    // fromJson
    buf.writeln();
    buf.writeln('  static fromJson(json: Record<string, unknown>): $name {');
    buf.writeln('    return plainToInstance($name, json, {');
    buf.writeln('      excludeExtraneousValues: true,');
    buf.writeln('    });');
    buf.writeln('  }');

    // toJson
    buf.writeln();
    buf.writeln('  toJson(): Record<string, unknown> {');
    buf.writeln(
        '    return instanceToPlain(this, { excludeExtraneousValues: true });');
    buf.writeln('  }');

    buf.writeln('}');
    buf.writeln();

    return buf.toString();
  }

  static void _emitField(
    StringBuffer buf,
    Map<String, dynamic> field,
    Set<String> modelNames,
    Set<String> enumNames,
  ) {
    final name = field['name'] as String;
    final jsonName = field['jsonName'] as String;
    final tsType = field['tsType'] as String;
    final isOptional = field['isOptional'] as bool;
    final hasConverter = field['hasConverter'] as bool;

    // @Expose
    final exposeNamePart = jsonName != name ? "{ name: '$jsonName' }" : '';
    buf.writeln('  @Expose($exposeNamePart)');

    // @IsOptional or validator
    if (isOptional) {
      buf.writeln('  @IsOptional()');
    }

    // Type-specific validators
    final baseType = tsType.replaceAll(' | undefined', '').replaceAll('[]', '');
    if (baseType == 'string') {
      buf.writeln('  @IsString()');
    } else if (baseType == 'number') {
      buf.writeln('  @IsNumber()');
    } else if (baseType == 'boolean') {
      buf.writeln('  @IsBoolean()');
    } else if (baseType == 'Date') {
      buf.writeln('  @IsDate()');
      if (hasConverter) {
        buf.writeln(
            '  @Transform(({ value }) => firestoreTimestampToDate(value), { toClassOnly: true })');
        buf.writeln(
            '  @Transform(({ value }) => dateToFirestoreTimestamp(value), { toPlainOnly: true })');
      }
    } else if (enumNames.contains(baseType)) {
      buf.writeln('  @IsEnum($baseType)');
    } else if (modelNames.contains(baseType)) {
      // Nested model
      buf.writeln('  @ValidateNested()');
      buf.writeln("  @Type(() => $baseType)");
    } else if (tsType.endsWith('[]')) {
      buf.writeln("  @Type(() => $baseType)");
    }

    // Field declaration
    final optionalMark = isOptional ? '?' : '';
    buf.writeln('  $name$optionalMark: $tsType;');
    buf.writeln();
  }
}
