class UtilsEmitter {
  static String emit() => r'''
// Auto-generated by ts_codegen. Do not edit manually.

/**
 * Represents a Firestore Timestamp.
 * Use this type instead of importing from firebase-admin/firestore
 * so the models package stays framework-agnostic.
 */
export interface FirestoreTimestamp {
  seconds: number;
  nanoseconds: number;
  toDate(): Date;
}

/**
 * Converts a Firestore Timestamp (or plain Date) to a JS Date.
 * Mirrors Dart's DateTimeNullableConverter.fromJson().
 */
export function firestoreTimestampToDate(
  value: FirestoreTimestamp | Date | string | null | undefined,
): Date | undefined {
  if (value == null) return undefined;
  if (value instanceof Date) return value;
  if (typeof value === 'string') return new Date(value);
  // Firestore Timestamp-like object
  if (typeof value === 'object' && 'seconds' in value) {
    return new Date((value as FirestoreTimestamp).seconds * 1000);
  }
  return undefined;
}

/**
 * Converts a JS Date back to a plain Firestore Timestamp-compatible object.
 * Mirrors Dart's DateTimeNullableConverter.toJson().
 */
export function dateToFirestoreTimestamp(
  value: Date | undefined | null,
): FirestoreTimestamp | null {
  if (value == null) return null;
  const seconds = Math.floor(value.getTime() / 1000);
  const nanoseconds = (value.getTime() % 1000) * 1e6;
  return {
    seconds,
    nanoseconds,
    toDate: () => value,
  };
}

/**
 * Type guard to check if a value is a Firestore Timestamp.
 */
export function isFirestoreTimestamp(value: unknown): value is FirestoreTimestamp {
  return (
    typeof value === 'object' &&
    value !== null &&
    'seconds' in value &&
    'nanoseconds' in value
  );
}

/**
 * Deeply converts all Firestore Timestamps in an object to JS Dates.
 * Useful for normalising raw Firestore documents before validation.
 */
export function normaliseTimestamps<T extends Record<string, unknown>>(obj: T): T {
  const result = { ...obj };
  for (const key in result) {
    const val = result[key];
    if (isFirestoreTimestamp(val)) {
      (result as Record<string, unknown>)[key] = firestoreTimestampToDate(val);
    } else if (val && typeof val === 'object' && !Array.isArray(val)) {
      (result as Record<string, unknown>)[key] = normaliseTimestamps(
        val as Record<string, unknown>,
      );
    }
  }
  return result;
}
''';
}
