class UtilsEmitter {
  static String emit() => r'''
// Auto-generated by ts_codegen. Do not edit manually.

import { BigQueryDate, BigQueryDatetime } from "@google-cloud/bigquery";
import { ClassConstructor, Transform, Type } from "class-transformer";
import { ValidateIf, ValidateNested } from "class-validator";
import { GeoPoint, Timestamp } from "firebase-admin/firestore";
import moment from "moment-timezone";

const TIMEZONE = "Asia/Kolkata";

export const isIso8601String = (str: unknown): str is string => {
  if (typeof str !== "string") return false;
  return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:/.test(str) && !isNaN(new Date(str).getTime());
};

export const dateToTimestamp = (value: any): Timestamp | undefined => {
  if (!value || typeof value !== "object") return undefined;
  if (value instanceof Timestamp) return value;

  const seconds = value.seconds ?? value._seconds;
  const nanoseconds = value.nanoseconds ?? value._nanoseconds;

  if (typeof seconds === "number" && typeof nanoseconds === "number") {
    return new Timestamp(seconds, nanoseconds);
  }
  return undefined;
};

export const toGeoPoint = (value: any): { latitude: number; longitude: number } | undefined => {
  if (!value || typeof value !== "object") return undefined;

  if (value instanceof GeoPoint) {
    return { latitude: value.latitude, longitude: value.longitude };
  }

  const lat = value.latitude ?? value._latitude;
  const lng = value.longitude ?? value._longitude;

  if (typeof lat === "number" && typeof lng === "number" && !isNaN(lat) && !isNaN(lng)) {
    return { latitude: lat, longitude: lng };
  }

  return undefined;
};

export const parseDate = (value: any): Date | undefined => {
  if (!value || value === "") return undefined;
  if (value instanceof Date) return value;
  if (isIso8601String(value)) return new Date(value);

  const ts = dateToTimestamp(value);
  if (ts) return ts.toDate();

  return undefined;
};

export const formatToIst = (value: any): Date | undefined => {
  const date = parseDate(value);
  return date ? moment(date).tz(TIMEZONE).toDate() : undefined;
};

export const TransformDate = () =>
  Transform(({ value }) => formatToIst(value), { toClassOnly: true });

export const TransformListDate = () =>
  Transform(
    ({ value }) =>
      Array.isArray(value)
        ? value.map(formatToIst).filter((d): d is Date => !!d)
        : value,
    { toClassOnly: true }
  );

export const OptionalValue = (): PropertyDecorator =>
  (target: object, propertyKey: string | symbol) => {
    ValidateIf((_, value) => value !== null && value !== undefined)(target, propertyKey);
  };

export const OptionalNested = <T extends object>(
  typeFn: () => ClassConstructor<T>
): PropertyDecorator =>
  (target: object, propertyKey: string | symbol) => {
    ValidateIf((_, value) => value !== null && value !== undefined)(target, propertyKey);
    ValidateNested()(target, propertyKey);
    Type(typeFn)(target, propertyKey);
  };

export const TransformGeoPoint = () =>
  Transform(({ value }) => {
    const geo = toGeoPoint(value);
    return geo ? new GeoPoint(geo.latitude, geo.longitude) : null;
  });

export const Default = (defaultValue: any) =>
  Transform(({ value, options }) =>
    value ?? (options?.exposeDefaultValues ? defaultValue : value)
  );

export const fromFunctionJson = (data: any): any => {
  if (data === null || data === undefined) return data;

  if (Array.isArray(data)) return data.map(fromFunctionJson);

  if (typeof data === "string" && isIso8601String(data)) return formatToIst(data);
  if (data instanceof Date) return formatToIst(data);
  if (data instanceof BigQueryDatetime || data instanceof BigQueryDate) return data.value;

  const ts = dateToTimestamp(data);
  if (ts) return formatToIst(ts.toDate());

  const geo = toGeoPoint(data);
  if (geo) return geo;

  if (typeof data === "object") {
    return Object.fromEntries(
      Object.entries(data).map(([key, val]) => [key, fromFunctionJson(val)])
    );
  }

  return data;
};

export const toFunctionJson = (data: any): any => {
  if (data === null || data === undefined) return data;

  if (Array.isArray(data)) return data.map(toFunctionJson);

  if (data instanceof Date) return moment(data).tz(TIMEZONE).format();
  if (data instanceof Timestamp) return moment(data.toDate()).tz(TIMEZONE).format();
  if (data instanceof BigQueryDatetime || data instanceof BigQueryDate) return data.value;

  if (typeof data === "object") {
    return Object.fromEntries(
      Object.entries(data).map(([key, val]) => [key, toFunctionJson(val)])
    );
  }

  return data;
};
''';
}
