import 'model_analyzer.dart';
import 'type_mapping.dart';
import 'cross_file_registry.dart';

/// Generates TypeScript + Zod schema strings from [ClassInfo] objects.
class ZodSchemaGenerator {
  final Map<String, ClassInfo> classRegistry;
  final GeneratorConfig config;
  final CrossFileRegistry? crossFileRegistry;
  final String? currentOutputFile;

  ZodSchemaGenerator({
    required this.classRegistry,
    required this.config,
    this.crossFileRegistry,
    this.currentOutputFile,
  });

  /// Generate full TS output for a list of classes.
  String generateFile(List<ClassInfo> classes) {
    final buf = StringBuffer();

    // Separate enums and models, preserve declaration order
    final enums = classes.where((c) => c.isEnum).toList();
    final models = classes.where((c) => !c.isEnum).toList();
    final sorted = _topologicalSort(models);

    // Collect all external type references for cross-file imports
    final externalRefs = _collectExternalTypeRefs(classes);

    // Header
    buf.writeln('// AUTO-GENERATED by dart_ts_generator. DO NOT EDIT.');
    buf.writeln('// Generated at: ${DateTime.now().toIso8601String()}');
    buf.writeln();

    // Zod + cross-file imports
    if (crossFileRegistry != null &&
        currentOutputFile != null &&
        externalRefs.isNotEmpty) {
      buf.writeln(ImportHeaderGenerator.generate(
        currentFile: currentOutputFile!,
        referencedTypes: externalRefs.toList(),
        registry: crossFileRegistry!,
        zodImport: config.zodImport,
      ));
    } else {
      buf.writeln("import { z } from '${config.zodImport}';");
    }
    buf.writeln();

    // Enums first
    for (final e in enums) {
      buf.writeln(_generateEnum(e));
    }

    if (enums.isNotEmpty) buf.writeln();

    // Models
    for (final m in sorted) {
      if (m.isAbstract && m.fields.isEmpty) continue;
      buf.writeln(_generateModel(m));
    }

    return buf.toString();
  }

  /// Collect type names that are referenced but NOT defined in [classes].
  Set<String> _collectExternalTypeRefs(List<ClassInfo> classes) {
    final localNames = classes.map((c) => c.name).toSet();
    final refs = <String>{};

    for (final cls in classes) {
      if (cls.superclassName != null &&
          !localNames.contains(cls.superclassName)) {
        refs.add(cls.superclassName!);
      }
      for (final field in cls.fields) {
        final typeName = field.dartTypeName;
        if (!localNames.contains(typeName)) {
          if (field.isModel || field.isEnum) refs.add(typeName!);
          // Also check list inner types
          for (final arg in field.typeArgs) {
            if (classRegistry.containsKey(arg) && !localNames.contains(arg)) {
              refs.add(arg!);
            }
          }
        }
      }
    }

    return refs;
  }

  String _generateEnum(ClassInfo info) {
    final values = info.enumValues.map((v) => '"$v"').join(', ');
    return '''export const ${info.name}Schema = z.enum([$values]);
export type ${info.name} = z.infer<typeof ${info.name}Schema>;
''';
  }

  String _generateModel(ClassInfo info) {
    final buf = StringBuffer();
    final schemaName = '${info.name}Schema';

    final parent = info.superclassName;
    final hasParent = parent != null &&
        (classRegistry.containsKey(parent) ||
            (crossFileRegistry?.hasType(parent) ?? false));

    if (hasParent) {
      buf.writeln('export const $schemaName = ${parent}Schema.extend({');
    } else {
      buf.writeln('export const $schemaName = z.object({');
    }

    for (final field in info.fields) {
      final zodExpr = _generateFieldZod(field);
      // Multi-line expressions get extra indent, single-line stay inline
      if (zodExpr.contains('\n')) {
        buf.writeln('  ${field.tsName}:');
        for (final line in zodExpr.split('\n')) {
          buf.writeln('    $line');
        }
        // Remove trailing comma from last line and add it at field level
        final lines = buf.toString().trimRight().split('\n');
        final last = lines.removeLast();
        buf.clear();
        buf.writeln(lines.join('\n'));
        buf.writeln('$last,');
      } else {
        buf.writeln('  ${field.tsName}: $zodExpr,');
      }
    }

    buf.writeln('});');
    buf.writeln();
    buf.writeln('export type ${info.name} = z.infer<typeof $schemaName>;');
    buf.writeln();

    return buf.toString();
  }

  String _generateFieldZod(FieldInfo field) {
    if (field.fromJson != null || field.toJson != null) {
      // Custom fromJson/toJson → treat as z.any()
      final base = field.isNullable ? 'z.any().optional()' : 'z.any()';
      if (field.defaultValue != null) {
        return '$base.default(${field.defaultValue})';
      }
      return base;
    }

    if (field.converterClass != null) {
      return _generateConverterZod(field);
    }

    return _generateTypeZod(field);
  }

  String _generateConverterZod(FieldInfo field) {
    final converter = field.converterClass!;
    String schema;

    // Check known converters
    ConverterTransform? transform;
    for (final entry in TypeMapping.knownConverters.entries) {
      if (converter.toLowerCase().contains(entry.key.toLowerCase())) {
        transform = entry.value;
        break;
      }
    }

    if (transform != null) {
      if (transform.isList || field.isList) {
        schema = '''z.array(
    z.any().transform(${transform.transform})
  )''';
      } else {
        schema = 'z.any().transform(${transform.transform})';
      }
    } else if (_isDateTimeConverter(converter)) {
      final nullable = converter.toLowerCase().contains('nullable');
      final t = nullable
          ? TypeMapping.knownConverters['DateTimeNullableConverter']!.transform
          : TypeMapping.knownConverters['DateTimeConverter']!.transform;
      schema = 'z.any().transform($t)';
    } else {
      schema = 'z.any()';
    }

    if (field.isNullable) schema = '$schema.optional()';
    if (field.defaultValue != null)
      schema = '$schema.default(${field.defaultValue})';

    return schema;
  }

  bool _isDateTimeConverter(String cls) {
    final lower = cls.toLowerCase();
    return lower.contains('datetime') || lower.contains('timestamp');
  }

  String _generateTypeZod(FieldInfo field) {
    String schema;

    if (field.isList) {
      schema = _generateListZod(field);
    } else if (field.isMap) {
      schema = _generateMapZod(field);
    } else if (field.isEnum) {
      schema = '${field.dartTypeName}Schema';
    } else if (field.isModel) {
      schema = '${field.dartTypeName}Schema';
    } else {
      schema = _resolveScalarZod(field.dartTypeName!);
    }

    if (field.isNullable) {
      schema = '$schema.optional()';
    }

    if (field.defaultValue != null) {
      schema = '$schema.default(${field.defaultValue})';
    }

    return schema;
  }

  String _generateListZod(FieldInfo field) {
    if (field.typeArgs.isEmpty) return 'z.array(z.unknown())';

    final innerType = field.typeArgs[0];

    // Check if inner type is an enum or model
    if (classRegistry.containsKey(innerType)) {
      final innerInfo = classRegistry[innerType]!;
      if (innerInfo.isEnum) {
        return 'z.array(${innerType}Schema)';
      }
      return 'z.array(${innerType}Schema)';
    }

    final innerZod = _resolveScalarZod(innerType!);
    return 'z.array($innerZod)';
  }

  String _generateMapZod(FieldInfo field) {
    if (field.typeArgs.length < 2) return 'z.record(z.unknown())';
    final valueType = field.typeArgs[1];
    final valueZod = classRegistry.containsKey(valueType)
        ? '${valueType}Schema'
        : _resolveScalarZod(valueType!);
    return 'z.record($valueZod)';
  }

  String _resolveScalarZod(String typeName) {
    if (TypeMapping.primitiveZodMap.containsKey(typeName)) {
      return TypeMapping.primitiveZodMap[typeName]!;
    }
    if (TypeMapping.timestampTypes.contains(typeName)) {
      return r'''z.any().transform((val) =>
    val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : val)''';
    }
    if (TypeMapping.opaqueFirestoreTypes.contains(typeName)) {
      return 'z.any()';
    }
    if (TypeMapping.firestoreZodMap.containsKey(typeName)) {
      return TypeMapping.firestoreZodMap[typeName]!;
    }
    // Unknown type → assume schema reference
    return '${typeName}Schema';
  }

  /// Topologically sort models so base classes come before derived ones.
  List<ClassInfo> _topologicalSort(List<ClassInfo> models) {
    final nameMap = {for (final m in models) m.name: m};
    final result = <ClassInfo>[];
    final visited = <String>{};

    void visit(ClassInfo cls) {
      if (visited.contains(cls.name)) return;
      visited.add(cls.name!);
      if (cls.superclassName != null &&
          nameMap.containsKey(cls.superclassName)) {
        visit(nameMap[cls.superclassName]!);
      }
      result.add(cls);
    }

    for (final m in models) {
      visit(m);
    }

    return result;
  }
}

class GeneratorConfig {
  final String outputDir;
  final bool generateIndex;
  final String zodImport;
  final bool firestoreTransforms;
  final bool nullSafety;

  const GeneratorConfig({
    this.outputDir = 'lib/generated/ts',
    this.generateIndex = true,
    this.zodImport = 'zod',
    this.firestoreTransforms = true,
    this.nullSafety = true,
  });

  factory GeneratorConfig.fromMap(Map<String, dynamic> map) {
    return GeneratorConfig(
      outputDir: map['output_dir'] as String? ?? 'lib/generated/ts',
      generateIndex: map['generate_index'] as bool? ?? true,
      zodImport: map['zod_import'] as String? ?? 'zod',
      firestoreTransforms: map['firestore_transforms'] as bool? ?? true,
      nullSafety: map['null_safety'] as bool? ?? true,
    );
  }
}
