// AUTO-GENERATED by dart_ts_generator. DO NOT EDIT.
// Generated at: 2024-01-15T00:00:00.000Z

import { z } from "zod";

// ─── Enums ────────────────────────────────────────────────────────────────────

export const EiAppSourceSchema = z.enum(["admin", "user", "other"]);
export type EiAppSource = z.infer<typeof EiAppSourceSchema>;

export const EiUserRoleSchema = z.enum(["rider", "admin", "superAdmin", "guest"]);
export type EiUserRole = z.infer<typeof EiUserRoleSchema>;

export const EiRideStatusSchema = z.enum(["pending", "active", "completed", "cancelled"]);
export type EiRideStatus = z.infer<typeof EiRideStatusSchema>;

// ─── EiAddress ────────────────────────────────────────────────────────────────

export const EiAddressSchema = z.object({
  street: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  postal_code: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
});
export type EiAddress = z.infer<typeof EiAddressSchema>;

// ─── EiModel ──────────────────────────────────────────────────────────────────

export const EiModelSchema = z.object({
  created_at:
    z.any().transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    ).optional(),

  updated_at:
    z.any().transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    ).optional(),

  added_on:
    z.any().transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    ).optional(),

  lastModifiedAppSource: EiAppSourceSchema.default("other"),
});
export type EiModel = z.infer<typeof EiModelSchema>;
