// AUTO-GENERATED by dart_ts_generator. DO NOT EDIT.
// Generated at: 2024-01-15T00:00:00.000Z

import { z } from "zod";

// ─────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────

export const EiAppSourceSchema = z.enum(["admin", "user", "other"]);
export type EiAppSource = z.infer<typeof EiAppSourceSchema>;

export const EiUserRoleSchema = z.enum(["rider", "admin", "superAdmin", "guest"]);
export type EiUserRole = z.infer<typeof EiUserRoleSchema>;

export const EiRideStatusSchema = z.enum(["pending", "active", "completed", "cancelled"]);
export type EiRideStatus = z.infer<typeof EiRideStatusSchema>;

// ─────────────────────────────────────────────────────────────
// ADDRESS (standalone nested model)
// ─────────────────────────────────────────────────────────────

export const EiAddressSchema = z.object({
  street: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  postal_code: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
});
export type EiAddress = z.infer<typeof EiAddressSchema>;

// ─────────────────────────────────────────────────────────────
// BASE MODEL
// ─────────────────────────────────────────────────────────────

export const EiModelSchema = z.object({
  created_at: z
    .any()
    .transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    )
    .optional(),

  updated_at: z
    .any()
    .transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    )
    .optional(),

  added_on: z
    .any()
    .transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    )
    .optional(),

  lastModifiedAppSource: EiAppSourceSchema.default("other"),
});
export type EiModel = z.infer<typeof EiModelSchema>;

// ─────────────────────────────────────────────────────────────
// USER (extends EiModel via .extend())
// ─────────────────────────────────────────────────────────────

export const EiUserSchema = EiModelSchema.extend({
  user_id: z.string().optional(),

  name: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),

  profile_photo_url: z.string().optional(),

  role: EiUserRoleSchema.default("rider"),

  isVerified: z.boolean().default(false),

  rating: z.number().default(0),

  totalRides: z.number().int().default(0),

  rider_categories: z.array(z.string()).default([]),

  kms_driven: z.number().default(0),

  address: EiAddressSchema.optional(),

  // Custom fromJson/toJson → opaque z.any()
  geoPoint: z.any().optional(),

  device_tokens: z.array(z.string()).default([]),

  blocked_user_ids: z.array(z.string()).default([]),

  // internalCache is @TsIgnore → omitted
});
export type EiUser = z.infer<typeof EiUserSchema>;

// ─────────────────────────────────────────────────────────────
// RIDE (extends EiModel, DateTime list converter)
// ─────────────────────────────────────────────────────────────

export const EiRideSchema = EiModelSchema.extend({
  ride_id: z.string().optional(),
  rider_id: z.string().optional(),
  driver_id: z.string().optional(),

  status: EiRideStatusSchema.default("pending"),

  pickupAddress: EiAddressSchema.optional(),
  dropAddress: EiAddressSchema.optional(),

  fare_amount: z.number().default(0),

  distance_km: z.number().default(0),

  started_at: z
    .any()
    .transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    )
    .optional(),

  ended_at: z
    .any()
    .transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    )
    .optional(),

  // List with DateTimeListConverter → array of transformed values
  checkpoint_times: z
    .array(
      z.any().transform((val) =>
        val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : val
      )
    )
    .default([]),
});
export type EiRide = z.infer<typeof EiRideSchema>;
