// AUTO-GENERATED by dart_ts_generator. DO NOT EDIT.
// Generated at: 2024-01-15T00:00:00.000Z

import { z } from "zod";
import { EiAddressSchema, EiModelSchema, EiRideStatusSchema } from "./ei_base.g";

// ─── EiRide ───────────────────────────────────────────────────────────────────

export const EiRideSchema = EiModelSchema.extend({
  ride_id: z.string().optional(),
  rider_id: z.string().optional(),
  driver_id: z.string().optional(),

  status: EiRideStatusSchema.default("pending"),

  pickupAddress: EiAddressSchema.optional(),
  dropAddress: EiAddressSchema.optional(),

  fare_amount: z.number().default(0),
  distance_km: z.number().default(0),

  started_at:
    z.any().transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    ).optional(),

  ended_at:
    z.any().transform((val) =>
      val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : null
    ).optional(),

  // @DateTimeListConverter() → array of individually transformed values
  checkpoint_times:
    z.array(
      z.any().transform((val) =>
        val?.toDate ? val.toDate() : typeof val === "number" ? new Date(val) : val
      )
    ).default([]),
});
export type EiRide = z.infer<typeof EiRideSchema>;
