// AUTO-GENERATED by dart_ts_generator. DO NOT EDIT.
// Generated at: 2024-01-15T00:00:00.000Z

import { z } from "zod";
import { EiAddressSchema, EiModelSchema, EiUserRoleSchema } from "./ei_base.g";

// ─── EiUser ───────────────────────────────────────────────────────────────────
// Extends EiModel → uses EiModelSchema.extend() so all base fields are inherited.

export const EiUserSchema = EiModelSchema.extend({
  user_id: z.string().optional(),
  name: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
  profile_photo_url: z.string().optional(),
  role: EiUserRoleSchema.default("rider"),
  isVerified: z.boolean().default(false),
  rating: z.number().default(0),
  totalRides: z.number().int().default(0),
  rider_categories: z.array(z.string()).default([]),
  kms_driven: z.number().default(0),
  address: EiAddressSchema.optional(),

  // @JsonKey(fromJson: ..., toJson: ...) → opaque z.any()
  geoPoint: z.any().optional(),

  device_tokens: z.array(z.string()).default([]),

  // internalCache is @TsIgnore → omitted entirely
});
export type EiUser = z.infer<typeof EiUserSchema>;
